DROP TABLE IF EXISTS USR_USER;
CREATE TABLE IF NOT EXISTS USR_USER (
    user_key NUMBER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_id VARCHAR(255),
    user_email VARCHAR(255),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_by NUMBER NOT NULL,
    modified_at TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS MST_ROLE;
CREATE TABLE IF NOT EXISTS MST_ROLE (
    role_key NUMBER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    role_id VARCHAR(255),
    role_name VARCHAR(255),
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_by NUMBER NOT NULL,
    modified_at TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE IF NOT EXISTS USER_ROLE (
    user_role_key NUMBER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_key NUMBER  NOT NULL,
    role_key NUMBER  NOT NULL,
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    modified_by NUMBER NOT NULL,
    modified_at TIMESTAMP NOT NULL
);


-- CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1 INCREMENT BY 1;